[package]
name = "AirDropPro"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
configparser = "3.1.0"
dirs = "6.0.0"
local-ip-address = "0.6.5"
log = "0.4.27"
mdns-sd = "0.15.0"
simplelog = "0.12.2"
